version: '3.8'

services:
  db:
    image: postgres:15.0-alpine
    container_name: tutorflow-postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: wektor
      POSTGRES_DB: tutorflow
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: tutorflow-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"

volumes:
  pgdata:
