package com.wziem.backend.controllers;

import com.wziem.backend.dtos.ReportDto;
import com.wziem.backend.dtos.ReportSummary;
import com.wziem.backend.services.ReportService;
import lombok.AllArgsConstructor;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@AllArgsConstructor
public class ReportController {


    private final ReportService reportService;


    //generate report for student
    @GetMapping("/students/{id}/report")
    public ResponseEntity<?> generateReport(@PathVariable(value = "id") Long studentId) {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        Long userId = (Long) authentication.getPrincipal(); //tutorId

        ReportDto report = reportService.generateReport(studentId, userId);

        return ResponseEntity.status(HttpStatus.CREATED).body(report);
    }

    //all reports generated by tutor
    @GetMapping("/reports")
    public ResponseEntity<?> getReports(){
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        Long userId = (Long) authentication.getPrincipal();
        List<ReportSummary> reports = reportService.getUsersReports(userId);

        return ResponseEntity.ok().body(reports);
    }

    //single report
    @GetMapping("/reports/{id}")
    public ResponseEntity<?> getSingleReport(@PathVariable(value = "id") Long reportId){
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        Long userId = (Long) authentication.getPrincipal();

        ReportDto report = reportService.getReport(userId, reportId);

        return ResponseEntity.ok().body(report);
    }

}
