spring:
  application:
    name: TutorFlow
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 #5min
    refreshTokenExpiration: 604800 #7day
server:
  port: 8080

app:
  upload:
    dir: ./uploads