spring:
  application:
    name: TutorFlow
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 #5min
    refreshTokenExpiration: 604800 #7day
server:
  port: 8080

app:
  google:
    drive:
      credentials: ${GOOGLE_DRIVE_CREDENTIALS}
      folder: 16t_FFvMAxs7vvpcuX7E5Wv75zQwztPtW
  system:
    prompt: ${SYSTEM_PROMPT}
  clientUrl: ${CLIENT_URL}

openai:
  api-key: ${OPENAI_API_KEY}
  base-url: https://api.openai.com/v1/chat/completions
  max-response-tokens: 800

stripe:
  api-key: ${STRIPE_API_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

